config/routes.rb
Demo::Application.routes.draw do
  get "say/hello"
  get "say/goodbye"
  get "say/show_files"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
    @time = Time.now
    @author = 'Ogre013'
  end

  def goodbye
  end
  
  def show_files
    @files = Dir.glob('*')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/say/goodbye.html.erb
<h1>Say#goodbye</h1>
<p>Очень приятно, что вы нас навестили</p>
<p>
Сказать <%= link_to 'привет', say_hello_path %> ещё раз.
</p

app/views/say/hello.html.erb
<h1>Say#hello</h1>
<p>
Сейчас: <%= @time  %>
</p>
<p>
Автор: <%= @author %>
</p>
<p>
Пора сказать  <%= link_to 'до свидания', say_goodbye_path %>!
</p>

<%= 1+2 %>
<%= 'cow' +'boy' %>
<%= 2.hour.from_now %>

app/views/say/show_files.html.erb
<h1>Soow</h1>
<p>Список файлов:</p>
<ul>
<% for file in @files %>
<li><%= file %></li>
<% end %>
</ul>